question_data = [
    {
        "category": "Science: Computers",
        "type": "boolean", "difficulty": "easy",
        "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]
    },
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What was the name given to Android 4.3?",
     "correct_answer": "Jelly Bean",
     "incorrect_answers": ["Lollipop", "Nutella", "Froyo"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The open source program Redis is a relational database server.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What is the correct term for the metal object in between the CPU and the CPU fan within a computer system?",
     "correct_answer": "Heat Sink",
     "incorrect_answers": ["CPU Vent", "Temperature Decipator", "Heat Vent"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
     "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What does LTS stand for in the software market?",
     "correct_answer": "Long Term Support",
     "incorrect_answers": ["Long Taco Service", "Ludicrous Transfer Speed",
                           "Ludicrous Turbo Speed"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "How fast is USB 3.1 Gen 2 theoretically?",
     "correct_answer": "10 Gb\/s",
     "incorrect_answers": ["5 Gb\/s", "8 Gb\/s", "1 Gb\/s"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What does &quot;LCD&quot; stand for?",
     "correct_answer": "Liquid Crystal Display",
     "incorrect_answers": ["Language Control Design", "Last Common Difference",
                           "Long Continuous Design"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which of these people was NOT a founder of Apple Inc?",
     "correct_answer": "Jonathan Ive",
     "incorrect_answers": ["Steve Jobs", "Ronald Wayne", "Steve Wozniak"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "What is the name given to layer 4 of the Open Systems Interconnection (ISO) model?",
     "correct_answer": "Transport",
     "incorrect_answers": ["Session", "Data link", "Network"]}]
#https://opentdb.com/api.php?amount=10&category=18